version: '3.7'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678" 
    environment:
      # Render arayüzünden ayarlanacaklar:
      # - GENERIC_TIMEZONE=Europe/Istanbul
      # - WEBHOOK_URL=https://YOUR_RENDER_APP_NAME.onrender.com/
      # - EXECUTIONS_PROCESS=main
      - N8N_USER_FOLDER=/var/n8n_data 
    volumes:
      - n8n_render_data:/var/n8n_data

volumes:
  n8n_render_data:
    # Bu, Render'ın kalıcı diskini kullanmak için bir Docker volume tanımıdır.
    # Render bu volume'u kendi kalıcı diskine otomatik olarak bağlayacaktır.
    # External: true gibi bir ayara genellikle gerek kalmaz Render'da.